apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: demo-voting-app
    name: vote-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
     app: demo-voting-app
     name: result-app-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: demo-voting-app
    name: redis-app-pod
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment
spec:
  selector:
    app: demo-voting-app
    name: postgres-pod
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

